variable "name" {}
variable "cloudaccount" {}
variable "region" {}
variable "sshkey" {}
variable "worker_min" {}
variable "worker_count" {}
variable "worker_max" {}
variable "worker_instance_type" {}
variable "worker_disk_size_gb" {}